version: '3.8'

services:
  db:
    image: mysql:8
    ports:
      - '7200:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'master1234'
      MYSQL_DB: 'eletrogamadb'
    volumes:
      - eletrogamadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
volumes:
  eletrogamadb: