version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '8080:8080'
  messager:
    build:
      context: .
      dockerfile: messager.Dockerfile
    ports:
      - '8081:8081'
