"""cria tabelas

Revision ID: a8a7a5cca3e9
Revises: 
Create Date: 2023-05-24 21:17:39.685163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a7a5cca3e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('idEndereco', sa.Integer(), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idEndereco')
    )
    op.create_index(op.f('ix_addresses_idEndereco'), 'addresses', ['idEndereco'], unique=False)
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=False)
    op.create_table('stations',
    sa.Column('idPosto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('statusFuncionamento', sa.String(length=100), nullable=True),
    sa.Column('precoKwh', sa.Float(), nullable=True),
    sa.Column('horarioFuncionamento', sa.String(length=100), nullable=False),
    sa.Column('tipoTomada', sa.String(length=100), nullable=False),
    sa.Column('potencia', sa.Integer(), nullable=False),
    sa.Column('idEndereco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEndereco'], ['addresses.idEndereco'], ),
    sa.PrimaryKeyConstraint('idPosto')
    )
    op.create_index(op.f('ix_stations_idPosto'), 'stations', ['idPosto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_idPosto'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_addresses_idEndereco'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
